version: 2
jobs:
  dist:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          command: npm i --registry=https://registry.npmjs.org/
      - run:
          command: npm run prod
      - run:
          command: npm run dist -- --publish never
  render:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          command: cd render && npm i --registry=https://registry.npmjs.org/ && npm run prod
workflows:
  version: 2
  dist:
    jobs:
      - dist
